const API_BASE = 'https://zarubinscky.app.n8n.cloud/webhook';
const REPORT_ENDPOINT = `${API_BASE}/report`;
const DELETE_ENDPOINT = `${API_BASE}/report-delete`;

const i18n = {
  en: {
    meetingReport: 'Meeting Report',
    generatedBy: 'Generated by MeetMind AI',
    downloadPdf: 'Download PDF',
    shareReport: 'Share Report',
    editReport: 'Edit Report',
    deleteReport: 'Delete Report',
    executiveSummary: 'Executive Summary',
    architecture: 'Architecture & Process',
    insights: 'Insights',
    decisions: 'Decisions',
    tasks: 'Tasks',
    owners: 'Owners',
    risks: 'Risks',
    transcript: 'Meeting Transcript',
    showTranscript: 'Show Full Meeting Transcript',
    hideTranscript: 'Hide Meeting Transcript',
    duration: 'Duration',
    participants: 'Participants',
    actionItems: 'Action Items',
    decisionCount: 'Decisions',
    riskCount: 'Risks',
    task: 'Task',
    owner: 'Owner',
    dueDate: 'Due Date',
    notSpecified: 'Not specified',
    copied: 'Report link copied.',
    deleted: 'This report has been deleted.',
    notFound: 'Report not found or no longer available.',
    missingToken: 'Report token is missing.',
    deleteTitle: 'Delete report from database?',
    deleteText: 'You will not be able to open it again.',
    deleteConfirm: 'Delete',
    cancel: 'Cancel',
    deleteDone: 'Report deleted.',
    deleteFailed: 'Could not delete report. Please try again later.',
    footerGenerated: 'Generated by MeetMind AI',
    footerTagline: 'Transform conversations into clarity.',
    footerCta: 'Create your own meeting report:'
  },
  ru: {
    meetingReport: 'Отчет по встрече',
    generatedBy: 'Generated by MeetMind AI',
    downloadPdf: 'Скачать PDF',
    shareReport: 'Поделиться',
    editReport: 'Редактировать',
    deleteReport: 'Удалить отчет',
    executiveSummary: 'Executive Summary',
    architecture: 'Architecture & Process',
    insights: 'Insights',
    decisions: 'Decisions',
    tasks: 'Tasks',
    owners: 'Owners',
    risks: 'Risks',
    transcript: 'Meeting Transcript',
    showTranscript: 'Показать полную расшифровку встречи',
    hideTranscript: 'Скрыть расшифровку встречи',
    duration: 'Длительность',
    participants: 'Участников',
    actionItems: 'Задач',
    decisionCount: 'Решения',
    riskCount: 'Риска',
    task: 'Задача',
    owner: 'Ответственный',
    dueDate: 'Срок',
    notSpecified: 'Не указано',
    copied: 'Ссылка на отчет скопирована.',
    deleted: 'Данный отчет был удален.',
    notFound: 'Отчет не найден или больше недоступен.',
    missingToken: 'Не передан токен отчета.',
    deleteTitle: 'Вы действительно хотите удалить отчет из базы данных?',
    deleteText: 'Вы больше не сможете открыть его по ссылке.',
    deleteConfirm: 'Удалить',
    cancel: 'Отменить',
    deleteDone: 'Отчет удален.',
    deleteFailed: 'Не удалось удалить отчет. Попробуйте позже.',
    footerGenerated: 'Generated by MeetMind AI',
    footerTagline: 'Transform conversations into clarity.',
    footerCta: 'Create your own meeting report:'
  },
  es: {},
  pt: {}
};

i18n.es = { ...i18n.en, meetingReport: 'Informe de reunión', deleted: 'Este informe ha sido eliminado.', notFound: 'Informe no encontrado o ya no disponible.' };
i18n.pt = { ...i18n.en, meetingReport: 'Relatório da reunião', deleted: 'Este relatório foi excluído.', notFound: 'Relatório não encontrado ou indisponível.' };

let currentMeeting = null;
let currentLang = 'en';
let currentToken = null;
let isEditMode = false;

const $ = (id) => document.getElementById(id);

function t(key) {
  return (i18n[currentLang] && i18n[currentLang][key]) || i18n.en[key] || key;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function isEmptyValue(value) {
  if (value == null) return true;
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === 'object') return Object.keys(value).length === 0;
  const normalized = String(value).replace(/[#*•\-\s.]/g, '').trim().toLowerCase();
  return !normalized || ['неуказано', 'not specified', 'n/a', 'none', 'null'].includes(normalized);
}

function normalizeReport(report = {}) {
  return {
       headline: report.headline || '',

    title: report.title || report.meeting_title || '',
    subtitle: report.subtitle || report.meeting_subtitle || '',
    objective: report.objective || report.meeting_objective || '',
    meeting_type: report.meeting_type || '',
    importance: report.importance || report.meeting_importance || '',
    importance_reason: report.importance_reason || '',

    summary: report.executive_brief || report.summary || '',
    architecture: report.architecture || { sections: [] },
    insights: toList(report.key_takeaways || report.insights),
    decisions: toList(report.decisions),
    key_metrics: toList(report.key_metrics || report.metrics),
    metrics: toList(report.metrics),
    risks: toList(report.risks),
    dependencies: toList(report.dependencies),
    tasks: toList(report.tasks),
    owners: toList(report.owners || report.responsibles),
    participants: Array.isArray(report.participants) ? report.participants : [],
    stats: report.stats || {}
  };
}

function toList(value) {
  if (Array.isArray(value)) {
    return value.filter((v) => !isEmptyValue(v));
  }

  if (isEmptyValue(value)) return [];
  return String(value)
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => line.replace(/^[-•]\s*/, '').trim())
    .filter((line) => !isEmptyValue(line));
 }

function parseTask(line) {
  const parts = String(line).split(/\s+—\s+|\s+-\s+/).map((p) => p.trim()).filter(Boolean);
  return {
    task: parts[0] || line,
    owner: parts[1] || '',
    dueDate: parts.slice(2).join(' — ') || ''
  };
}

function parseOwner(owner) {
    if (owner && typeof owner === 'object') {
        return {
            name: owner.name || owner.owner || owner.person || '',
            role: owner.role || owner.title || ''
        };
    }
    const parts = String(owner)
        .split(/\s+–\s+|\s+-\s+/)
        .map(p => p.trim())
        .filter(Boolean);
    return {
        name: parts[0] || owner,
        role: parts.slice(1).join(' – ')
    };
}

function initials(name) {
  return String(name || '')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0])
    .join('')
    .toUpperCase() || 'M';
}

function formatDate(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const locale = currentLang === 'ru' ? 'ru-RU' : currentLang === 'es' ? 'es-ES' : currentLang === 'pt' ? 'pt-PT' : 'en-US';
  return new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'long', year: 'numeric' }).format(date);
}

function durationLabel(seconds) {
  const s = Number(seconds);
  if (!s || s <= 0) return '';
  const minutes = Math.round(s / 60);
  return `${minutes} ${currentLang === 'ru' ? 'мин' : 'min'}`;
}

function renderTextBlock(text) {
  if (isEmptyValue(text)) return '';

  const lines = String(text).split('\n').map((l) => l.trim()).filter(Boolean);
  if (!lines.length) return '';

  const html = [];
  let listOpen = false;

  for (const line of lines) {
    const bullet = line.match(/^[-•]\s+(.*)$/);
    if (bullet) {
      if (!listOpen) {
        html.push('<ul>');
        listOpen = true;
      }
      html.push(`<li>${escapeHtml(bullet[1])}</li>`);
    } else {
      if (listOpen) {
        html.push('</ul>');
        listOpen = false;
      }
      html.push(`<p>${escapeHtml(line)}</p>`);
    }
}
  
  if (listOpen) html.push('</ul>');
  return html.join('');
}

function renderArchitecture(architecture) {

    if (!architecture) return '';
    const sections = architecture.sections || [];
    if (!sections.length) return '';
    return sections.map(section => {
        const items = section.items || [];

        if (!items.length) return '';

        return `
            <div class="architecture-section">
                <h3 class="architecture-section-title">
                    ${escapeHtml(section.title || '')}
                </h3>

                <div class="architecture-${section.layout}">

                    ${items.map(item => `
                        <div class="architecture-item">
                            <h4>${escapeHtml(item.title || '')}</h4>
                            <p>${escapeHtml(item.description || '')}</p>
                        </div>
                    `).join('')}
                </div>
            </div>
        `;
    }).join('');
}

function showToast(message) {
  const toast = $('toast');
  toast.textContent = message;
  toast.classList.remove('hidden');
  setTimeout(() => toast.classList.add('hidden'), 2600);
}

function showError(message) {
  $('loadingState').classList.add('hidden');
  $('reportPage').classList.add('hidden');
  $('errorTitle').textContent = message === t('deleted') ? t('deleted') : 'MeetMind Report';
  $('errorText').textContent = message;
  $('errorState').classList.remove('hidden');
}

function setLabels() {
  $('downloadPdfBtn').textContent = t('downloadPdf');
  $('shareBtn').textContent = t('shareReport');
  $('deleteBtn').textContent = t('deleteReport');
  $('deleteModalTitle').textContent = t('deleteTitle');
  $('deleteModalText').textContent = t('deleteText');
  $('confirmDeleteBtn').textContent = t('deleteConfirm');
  $('cancelDeleteBtn').textContent = t('cancel');
  $('transcriptToggleLabel').textContent = t('showTranscript');
  $('brandingFooter').innerHTML = `<strong>${escapeHtml(t('footerGenerated'))}</strong><span>${escapeHtml(t('footerTagline'))}</span><span>${escapeHtml(t('footerCta'))} <a href="https://zarubinscky.github.io/meetmind-report/">meetmind.ai</a></span>`;
}

function renderMeta(meeting, report) {
  const items = [];
  const date = formatDate(meeting.created_at);
  const duration = durationLabel(report.stats?.duration_seconds || meeting.duration_seconds);

  if (date) items.push(`<span class="meta-item">📅 ${escapeHtml(date)}</span>`);
  if (duration) items.push(`<span class="meta-item">🕘 ${escapeHtml(duration)}</span>`);
  items.push(`<span class="meta-item">— ${escapeHtml(t('generatedBy'))}</span>`);

  $('meetingMeta').innerHTML = items.join('');
}

function renderStats(report) {
  const stats = [];
  const duration = durationLabel(report.stats?.duration_seconds);
  const participantsCount = report.participants?.length || 0;
  const tasksCount = report.tasks.length;
  const decisionsCount = report.decisions.length;
  const risksCount = report.risks.length;

  if (duration) stats.push({ icon: '⏱', value: duration, label: t('duration') });
  if (participantsCount > 0) stats.push({ icon: '👥', value: participantsCount, label: t('participants') });
  if (tasksCount > 0) stats.push({ icon: '☑', value: tasksCount, label: t('actionItems') });
  if (decisionsCount > 0) stats.push({ icon: '⚖', value: decisionsCount, label: t('decisionCount') });
  if (risksCount > 0) stats.push({ icon: '⚠', value: risksCount, label: t('riskCount') });

  if (!stats.length) return;

  $('statsSection').innerHTML = stats.map((s) => `
    <div class="stat-item">
      <div class="stat-icon">${escapeHtml(s.icon)}</div>
      <div><div class="stat-value">${escapeHtml(s.value)}</div><div class="stat-label">${escapeHtml(s.label)}</div></div>
    </div>
  `).join('');
  $('statsSection').classList.remove('hidden');
}

function renderMetrics(report) {

  const metrics = report.key_metrics || report.metrics || [];
  if (!Array.isArray(metrics) || !metrics.length) return;
  const grid = $('metricsContent');
  let cols = metrics.length;
  if (metrics.length >= 7) {
    cols = 4;
  }

  grid.style.setProperty('--metric-cols', cols);
  grid.innerHTML = metrics.map(metric => `
    <div class="metric-card">
      <div class="metric-label">${escapeHtml(metric.label || '')}</div>
      <div class="metric-value">${escapeHtml(metric.value || '')}</div>
    </div>
  `).join('');
  $('metricsSection').classList.remove('hidden');
}

function renderDynamicCards(report) {
  const blocks = [];
  
  if (report.insights?.length) {
    blocks.push({
      key: 'insights',
      title: t('insights'),
      items: report.insights
    });
  }

  if (report.decisions?.length) {
    blocks.push({
      key: 'decisions',
      title: t('decisions'),
      items: report.decisions
    });
  }

  if (report.risks?.length) {
    blocks.push({
      key: 'risks',
      title: t('risks'),
      items: report.risks
    });
  }

  if (!blocks.length) return;
  const grid = $('insightsDecisionsRisksGrid');
  grid.style.setProperty('--grid-cols', 1);
  const sectionsHtml = blocks.map(block => {

    const html = block.items.map(item => {
      // Старый формат (строка)
      if (typeof item === 'string') {
        return `
          <div class="report-item">
            <span class="report-dot"></span>
            <div>${escapeHtml(item)}</div>
          </div>
        `;
      }
      // Новый формат (объект)
      return `
        <div class="report-item">
          <span class="report-dot"></span>
          <div>
            <strong>${escapeHtml(item.title || '')}</strong>
            ${
              item.details
                ? `<div class="item-description">${escapeHtml(item.details)}</div>`
                : ''
            }
          </div>
        </div>
      `;
    }).join('');

    return `
    <div class="highlight-section ${block.key}">
   <h3>${escapeHtml(block.title)}</h3>
    <div class="item-list">
        ${html}
    </div>
</div>
    `;
  }).join('');
  grid.innerHTML = `
<section class="dynamic-card highlights">
    ${sectionsHtml}
</section>
`;
grid.classList.remove('hidden');
}

function renderTasksAndOwners(report) {

  console.log('owners:', report.owners);
  console.log('tasks:', report.tasks);
  
  const hasTasks = report.tasks.length > 0;
  const hasOwners = report.owners.length > 0;
  if (!hasTasks && !hasOwners) return;

  function normalizeTask(item) {
    if (typeof item === 'string') return parseTask(item);

    return {
      task: item.task || item.title || '',
      owner: item.owner || '',
      dueDate: item.due_date || item.dueDate || '',
      priority: item.business_priority || item.priority || ''
    };
  }

  function visible(value) {
    return value && value !== 'Не указано' && value !== 'Not specified';
  }

  if (hasTasks) {
    const tasks = report.tasks.map(normalizeTask).filter((task) => !isEmptyValue(task.task));

    $('tasksContent').innerHTML = `
      <table class="task-table">
        <thead>
          <tr>
            <th>${escapeHtml(t('task'))}</th>
            <th>${escapeHtml(t('owner'))}</th>
            <th>${escapeHtml(t('dueDate'))}</th>
          </tr>
        </thead>
        <tbody>
          ${tasks.map((task) => `
            <tr>
              <td>${escapeHtml(task.task)}</td>
              <td>${visible(task.owner) ? escapeHtml(task.owner) : '—'}</td>
              <td>${visible(task.dueDate) 
                ? `<span class="due-badge">${escapeHtml(task.dueDate)}</span>`
                : '—'}
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="task-cards">
        ${tasks.map((task) => `
          <div class="task-card">
            <strong>${escapeHtml(task.task)}</strong>
            ${visible(task.owner) ? `<span>${escapeHtml(t('owner'))}: ${escapeHtml(task.owner)}</span>` : ''}
            ${visible(task.dueDate) ? `<span>${escapeHtml(t('dueDate'))}: ${escapeHtml(task.dueDate)}</span>` : ''}
          </div>
        `).join('')}
      </div>
    `;

    $('tasksSection').classList.remove('hidden');
  }

  if (hasOwners) {
    $('ownersContent').innerHTML = report.owners.map(parseOwner).map((owner) => `
      <div class="owner-card">
        <div class="owner-avatar">${escapeHtml(initials(owner.name))}</div>
        <div>
          <div class="owner-name">${escapeHtml(owner.name)}</div>
          ${owner.role ? `<div class="owner-role">${escapeHtml(owner.role)}</div>` : ''}
        </div>
      </div>
    `).join('');

    $('ownersSection').classList.remove('hidden');
}
}

function renderTranscript(transcript) {
  if (isEmptyValue(transcript)) return;
  $('transcriptContent').textContent = transcript;
  $('transcriptSection').classList.remove('hidden');
}

function renderReport(payload) {
  const meeting = payload.meeting;
  currentMeeting = meeting;
  currentLang = ['en', 'ru', 'es', 'pt'].includes(meeting.language) ? meeting.language : 'en';
  setLabels();

  if (meeting.status === 'deleted' || meeting.deleted_at) {
    showError(t('deleted'));
    return;
  }

  const report = normalizeReport(meeting.report || {});
  const title =
    meeting.meeting_title ||
    meeting.title ||
    report.meeting_title ||
    report.title ||
    t('meetingReport');
  
  document.title = `${title} — MeetMind AI`;
  $('meetingTitle').textContent = title;

  renderMeta(meeting, report);
  renderStats(report);
  renderMetrics(report);
  
  if (!isEmptyValue(report.summary)) {
    $('summaryContent').innerHTML = renderTextBlock(report.summary);
    $('summarySection').classList.remove('hidden');
  }

renderDynamicCards(report);
renderTasksAndOwners(report);

let hasDetails = false;

if (!isEmptyValue(report.architecture)) {
  $('architectureContent').innerHTML = renderArchitecture(report.architecture);
  $('architectureSection').classList.remove('hidden');
  hasDetails = true;
}

renderTranscript(meeting.transcript);
if (!isEmptyValue(meeting.transcript)) {
  hasDetails = true;
}

if (report.owners && report.owners.length > 0) {
  hasDetails = true;
}

if (hasDetails) {
  $('detailsSection').classList.remove('hidden');
}

  if (meeting.branding_visible === false) $('brandingFooter').classList.add('hidden');

  $('loadingState').classList.add('hidden');
  $('reportPage').classList.remove('hidden');
}

async function loadReport() {
  const params = new URLSearchParams(window.location.search);
  currentToken = params.get('token');

  if (!currentToken) {
    showError(i18n.en.missingToken);
    return;
  }

  try {
    const response = await fetch(`${REPORT_ENDPOINT}?token=${encodeURIComponent(currentToken)}`);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const payload = await response.json();

    if (!payload.success || !payload.meeting) {
      currentLang = payload.language || 'en';
      showError(t('notFound'));
      return;
    }

    renderReport(payload);
  } catch (error) {
    console.error(error);
    showError(i18n.en.notFound);
  }
}

function bindActions() {
  $('downloadPdfBtn').addEventListener('click', () => window.print());

  $('shareBtn').addEventListener('click', async () => {
    const url = window.location.href;
    const title = currentMeeting?.title || t('meetingReport');

    if (navigator.share) {
      try {
        await navigator.share({ title, url });
        return;
      } catch (error) {
        if (error.name === 'AbortError') return;
      }
    }
    
    await navigator.clipboard.writeText(url);
    showToast(t('copied'));
  });
  
  $('editReportBtn').addEventListener('click', toggleEditMode);
  $('deleteBtn').addEventListener('click', () => $('deleteModal').classList.remove('hidden'));
  $('cancelDeleteBtn').addEventListener('click', () => $('deleteModal').classList.add('hidden'));

  $('confirmDeleteBtn').addEventListener('click', async () => {
    if (!currentToken) return;

    try {
      const response = await fetch(`${DELETE_ENDPOINT}?token=${encodeURIComponent(currentToken)}`, { method: 'POST' });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      $('deleteModal').classList.add('hidden');
      showToast(t('deleteDone'));
      setTimeout(() => showError(t('deleted')), 600);
    } catch (error) {
      console.error(error);
      showToast(t('deleteFailed'));
    }
  });

$('detailsToggle').addEventListener('click', () => {
  const content = $('detailsContent');
  const expanded = !content.classList.contains('hidden');

  content.classList.toggle('hidden', expanded);
  $('detailsToggle').setAttribute('aria-expanded', String(!expanded));
  $('detailsToggleArrow').textContent = expanded ? '▼' : '▲';
});
  
  $('transcriptToggle').addEventListener('click', () => {
    const content = $('transcriptContent');
    const expanded = !content.classList.contains('hidden');
    content.classList.toggle('hidden', expanded);
    $('transcriptToggle').setAttribute('aria-expanded', String(!expanded));
    $('transcriptToggleLabel').textContent = expanded ? t('showTranscript') : t('hideTranscript');
  });
}

bindActions();
function toggleEditMode() {
    isEditMode = !isEditMode;
    document.body.classList.toggle('edit-mode', isEditMode);
    $('editReportBtn').textContent =
        isEditMode ? 'Save Changes' : 'Edit Report';
    console.log('Edit mode:', isEditMode);
}
loadReport();
