/*
 * MeetMind AI
 * Executive PDF Generator
 */

'use strict';

const PDF_CONFIG = {
    pageWidth: 1280,
    pageHeight: 720,
    fileSuffix: ' - MeetMind AI.pdf'
};

function sanitizePdfFilename(value) {
    return String(value || 'Meeting Report')
        .replace(/[\\/:*?"<>|]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
}

function getPdfTitle() {
    return (
        currentMeeting?.meeting_title ||
        currentMeeting?.title ||
        currentMeeting?.report?.meeting_title ||
        currentMeeting?.report?.title ||
        document.querySelector('.editable-title')?.innerText ||
        'Meeting Report'
    );
}

function isPdfValueVisible(value) {
    return value !== null &&
        value !== undefined &&
        String(value).trim() !== '' &&
        value !== 'Не указано' &&
        value !== 'Not specified';
}

function normalizePdfItem(item) {
    if (typeof item === 'string') {
        return {
            title: item,
            details: ''
        };
    }

    return {
        title: item.title || item.task || item.name || '',
        details: item.details || item.description || item.owner || item.due_date || item.dueDate || ''
    };
}

function buildPdfBlocks(report) {
    const blocks = [];

    if (isPdfValueVisible(report.summary)) {
        blocks.push({
            key: 'summary',
            title: 'Executive Summary',
            type: 'summary',
            priority: 100,
            items: [{ title: report.summary, details: '' }]
        });
    }

    if ((report.insights || []).length) {
        blocks.push({
            key: 'insights',
            title: 'Insights',
            type: 'list',
            priority: 90,
            items: report.insights.map(normalizePdfItem)
        });
    }

    if ((report.decisions || []).length) {
        blocks.push({
            key: 'decisions',
            title: 'Decisions',
            type: 'list',
            priority: 95,
            items: report.decisions.map(normalizePdfItem)
        });
    }

    if ((report.risks || []).length) {
        blocks.push({
            key: 'risks',
            title: 'Risks',
            type: 'list',
            priority: 85,
            items: report.risks.map(normalizePdfItem)
        });
    }

    if ((report.tasks || []).length) {
        blocks.push({
            key: 'tasks',
            title: 'Tasks',
            type: 'tasks',
            priority: 95,
            items: report.tasks.map(normalizePdfItem)
        });
    }

    return blocks.sort((a, b) => b.priority - a.priority);
}

function renderPdfBlock(block) {

    if (block.type === 'summary') {
        return `
            <div class="pdf-card pdf-card-summary">
                <h2>${block.title}</h2>
                <p>${block.items[0].title}</p>
            </div>
        `;
    }
    return `
        <div class="pdf-card">
            <h2>${block.title}</h2>
            <ul>
                ${block.items.map(item => `
                    <li>
                        <strong>${item.title}</strong>
                        ${item.details ? `<div>${item.details}</div>` : ''}
                    </li>
                `).join('')}
            </ul>
        </div>
    `;
}

function createPdfDOM() {
    const root = document.createElement('div');
    const report = currentMeeting?.report || {};
    const blocks = buildPdfBlocks(report);
    
    root.className = 'pdf-root';
    root.innerHTML = `
        <div class="pdf-slide">
            <div class="pdf-header">
                <div class="pdf-brand">
                    <img src="logo.png" alt="MeetMind AI" class="pdf-logo">
                    <span>MeetMind AI</span>
                </div>
                <div class="pdf-label">Executive PDF</div>
            </div>
            
          <div class="pdf-body">
            <h1>${getPdfTitle()}</h1>
          </div>

            <div class="pdf-footer">
                <div>Generated by MeetMind AI</div>
                <div>
                    <a href="https://meetmind.ai">meetmind.ai</a>
                    <span>·</span>
                    <a href="https://t.me/meetmind_ai_bot">Open in Telegram</a>
                </div>
            </div>
        </div>
    `;
    return root;
}

async function generateExecutivePdf() {
    const pdfRoot = createPdfDOM();
    document.body.appendChild(pdfRoot);
    await new Promise(resolve => requestAnimationFrame(resolve));
    const filename =
        sanitizePdfFilename(getPdfTitle()) +
        PDF_CONFIG.fileSuffix;
    const options = {
        margin: 0,
        filename,
        image: {
            type: 'jpeg',
            quality: 1
        },
        html2canvas: {
            scale: 2,
            useCORS: true
        },
        jsPDF: {
            unit: 'px',
            format: [PDF_CONFIG.pageWidth, PDF_CONFIG.pageHeight],
            orientation: 'landscape'
        }
    };
    try {
        await html2pdf()
            .set(options)
            .from(pdfRoot)
            .save();
    } finally {
        pdfRoot.remove();
    }
}

    
