/*
 * MeetMind AI
 * Executive PDF Generator
 */

'use strict';

const PDF_CONFIG = {
    pageWidth: 1280,
    pageHeight: 720,
    fileSuffix: ' - MeetMind AI.pdf'
};

function sanitizePdfFilename(value) {
    return String(value || 'Meeting Report')
        .replace(/[\\/:*?"<>|]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
}

function getPdfTitle() {
    return (
        currentMeeting?.meeting_title ||
        currentMeeting?.title ||
        currentMeeting?.report?.meeting_title ||
        currentMeeting?.report?.title ||
        document.querySelector('.editable-title')?.innerText ||
        'Meeting Report'
    );
}

function createPdfDOM() {
    const root = document.createElement('div');
    root.className = 'pdf-root';
    root.innerHTML = `
        <div class="pdf-slide">
            <div class="pdf-header">
                <div class="pdf-brand">
                    <img src="logo.png" alt="MeetMind AI" class="pdf-logo">
                    <span>MeetMind AI</span>
                </div>
                <div class="pdf-label">Executive PDF</div>
            </div>
            <div class="pdf-body">
                <h1>${getPdfTitle()}</h1>
                <div class="pdf-summary">
    ${currentMeeting?.report?.summary || ''}
</div>
            </div>
            <div class="pdf-footer">
                <div>Generated by MeetMind AI</div>
                <div>
                    <a href="https://meetmind.ai">meetmind.ai</a>
                    <span>·</span>
                    <a href="https://t.me/meetmind_ai_bot">Open in Telegram</a>
                </div>
            </div>
        </div>
    `;
    return root;
}

async function generateExecutivePdf() {
    
    const pdfRoot = createPdfDOM();
    document.body.appendChild(pdfRoot);
    await new Promise(resolve => requestAnimationFrame(resolve));
    
    const title = sanitizePdfFilename(getPdfTitle());
    const filename = `${title}${PDF_CONFIG.fileSuffix}`;
    const options = {
        margin: 0,
        filename,
        image: {
            type: 'jpeg',
            quality: 1
        },
        html2canvas: {
            scale: 2,
            useCORS: true
        },
        jsPDF: {
            unit: 'px',
            format: [PDF_CONFIG.pageWidth, PDF_CONFIG.pageHeight],
            orientation: 'landscape'
        }
    };
    try {
        await html2pdf()
            .set(options)
            .from(pdfRoot)
            .save();
    } finally {
        pdfRoot.remove();
    }
}

    
