(function () {

    "use strict";

    window.FooterRenderer = {

        render(report){

            const generatedAt =
                report?.generated_at ||
                report?.generatedAt ||
                "";

            return RenderHelpers.section(

                "",

                RenderHelpers.card(`

                    <div class="mm-footer">

                        <div class="mm-footer-left">

                            Generated by <strong>MeetMind AI</strong>

                        </div>

                        <div class="mm-footer-right">

                            ${
                                generatedAt
                                    ? RenderHelpers.escape(generatedAt)
                                    : ""
                            }

                        </div>

                    </div>

                `),

                "mm-footer-section"

            );

        }

    };

})();
